### ISSUE TITLE
Deploy GIVpower unipool contract on Polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giv-token-contracts#100]

**Comment by mohammadranjbarz** [comment]
@laurenluz  We deployed the contracts on the testnet chain (Cardona) once tests passed we can deploy them on  mainnet

**Comment by laurenluz** [comment]
make sure you update the deployment notion doc w/ the unipool contract on zkEVM mainnet.. and this is done, right?

**Comment by mohammadranjbarz** [comment]
> make sure you update the deployment notion doc w/ the unipool contract on zkEVM mainnet.. and this is done, right?


I added them here 

Cardona: https://www.notion.so/giveth/a521deb4b9604e3bbe56a90f8b6436d3?v=f5e880fc0c81457b974fb89fa7a01ba9
Mainnet: https://www.notion.so/giveth/641e512e33124a249177f67ba4762044?v=86ba47af2a9a4927a68cf0a8fcbe5c7d
