### ISSUE TITLE
Deploy GIV token distro contract on Polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giv-token-contracts#101]

**Comment by mohammadranjbarz** [comment]
@laurenluz  We deployed the contracts on the testnet chain (Cardona) once tests passed we can deploy them on  mainnet

**Comment by laurenluz** [comment]
@mohammadranjbarz I think we have deployed by now on zkEVM mainnet too, right? is everything workings as expected?

Let's make sure we are updating our notion doc with all the contract addreses we deploy on mainnet. https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I think we have deployed by now on zkEVM mainnet too, right? is everything workings as expected?
> 
> Let's make sure we are updating our notion doc with all the contract addreses we deploy on mainnet. https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229

Yeah everything seems fine, these are the notion files I have added
