### ISSUE TITLE
Fix issues reported by lastperson

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giv-token-contracts#68]
https://github.com/lastperson/code-reviews/blob/main/Giveth%20GIVeconomy%20Contracts%20Code%20Review.pdf

**Comment by divine-comedian** [comment]
@aminlatifi  is this issue still relevant?

**Comment by aminlatifi** [comment]
@divine-comedian I double-checked them, we can close this since some are addressed and other minor issues were on contracts like bridge token that's not deployed as part of giveconomy.
